version: '3.8'

services: 
  calendar:
    build: ./
    command: ./check-out-db.sh db ./calendar
    ports: 
      - 8000:8000
    depends_on: 
      - db
    environment:
      - DB_PASSWORD=qwerty1234

  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty1234
    ports:
      - 5438:5432
volumes:
  db_data:
