version: '3.8'

app: 
  calendar:
    build: ./
    command: ./wait-for-postgres.sh db ./calendar
    ports: 
      - 8000:8000
    depends-on: 
      - db
    enviroment:
      - DB_PASSWORD=qwerty1234

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    enviroment:
      - POSTGRES_PASSWORD=qwerty1234
    ports:
      - 5438:5432

